# Generated by Django 3.1.7 on 2021-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('years_old', models.IntegerField()),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=30)),
                ('obervation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
    ]
